---
- name: simple ansible ping to do some testing
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: test connection to managed hosts via ansible ping
      ping:

    - name: gather facts with subset set to '!all'
      setup:
        gather_subset: '!all'
